services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
  
  backend:
    build: ./server
    restart: always
    expose:
      - 8971

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
